### ISSUE TITLE
Missing config for specifying version for pip package `docker-py` version

### ISSUE THREAD

**Issue by PikachuEXE** [angstwad/docker.ubuntu#27] opened 2014-12-24 08:27 UTC
I am using docker `1.3.3`, and `docker-py` `0.6.0`.
On a new machine, I found out this role installed `docker-py` `0.7.0`, which uses a newer API version, and return error on every docker module task.

My current "fix":
```yaml
---
- name: Remove Docker-py with wrong version
  pip:
    name: "docker-py"
    state: "absent"
- name: Install Docker-py with correct version
  pip:
    name: "docker-py"
    state: "present"
    version: 0.6.0
```

**Comment by angstwad** [comment] 2015-03-01 15:03
Unfortunately dockerpy and docker releases aren't always in sync.  I've seen several such issues where dockerpy adds API calls not yes released in the stable docker API. I'm not sure we should attempt to resolve this issue in this role, since the issue is upstream, intermittent, and unpredictable.

It's good info to know, regardless.  Thanks.

**Closed by angstwad** 2015-03-01 15:03 UTC
